services:
    Github\Client:
        arguments:
            - '@Github\HttpClient\Builder'
        calls:
            - ['authenticate', ['%env(CUSTOM_GITHUB_TOKEN)%', null, 'access_token_header']]

    Github\HttpClient\Builder:
        arguments:
            - '@?Http\Client\HttpClient'
            - '@?Psr\Http\Message\RequestFactoryInterface'
            - '@?Psr\Http\Message\StreamFactoryInterface'
