index:
    path: /{version}
    controller: App\Controller\StartpageController::index
    methods: GET
    defaults:
        version: '%pr_target_branch%'

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
