index:
    path: /
    controller: App\Controller\StartpageController::index
    methods: GET

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
