name: Generate data files

on:
  schedule:
    - cron: '0 6,12,18 * * *'
  push:
    branches:
      - master

jobs:
  build:
    name: Generate
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.1.2
        with:
          php-version: 7.4

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'source'

      - name: Checkout Symfony repo
        run: git clone https://github.com/symfony/symfony symfony

      - name: Download dependencies
        run: |
          cd source
          composer install --no-interaction --optimize-autoloader

      - name: Generate data files
        run: |
          WORKDIR=$(pwd)
          cd $WORKDIR/symfony && git checkout 4.4
          cd $WORKDIR/source && php bin/console app:trans-stats $WORKDIR/symfony > config/data/4.4.json
          cd $WORKDIR/symfony && git checkout 5.2
          cd $WORKDIR/source && php bin/console app:trans-stats $WORKDIR/symfony > config/data/5.2.json

      - name: Commit & push the new files
        id: commit_push
        run: |
          echo "::group::git status"
          cd source
          git status
          echo "::endgroup::"

          git add -N .
          if [[ $(git diff --numstat | wc -l) -eq 0 ]]; then
            echo "No changes found. Exiting."
            echo "::set-output name=publish::false"
            exit 0;
          fi

          git config --local user.email "noreply@github.com"
          git config --local user.name "GitHub Bot"

          echo "::group::git push"
          git add .
          git commit -m "Update data files"
          git push
          echo "::endgroup::"
          echo "::set-output name=publish::true"

      - name: Build website
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: |
          cd source
          bin/console app:build-website

      - name: Deploy website
        if: ${{ github.event_name == 'push' || steps.commit_push.outputs.publish == 'true' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-central-1"
        run: aws s3 sync ./source/build s3://symfony-translations.nyholm.tech --cache-control max-age=7200
